## Sathish's Notebook

## "R" programming

## Objects

Object >Stores the information& can be re-used whenever they required

In [1]:
#Assigning value to objects
# <- is used to assign values
a <- 100
a

[1] 100

In [2]:
Name <- "sathish"
Name

[1] "sathish"

In [3]:
d = TRUE # unlike python whole true/false word is capital in R.
D = FALSE
D

[1] FALSE

## CLEAN UP

Clear environment

In [4]:
rm(list = ls()) 
#rm() function in R Language is used to delete objects from the memory

Clear console

In [5]:
cat("\014")  # ctrl+L

## Functions in R

In [4]:
min(10,20,30,4,5)

[1] 4

In [5]:
max(10,20,30,4,5)

[1] 30

## Null values

na.rm in r refers to the logical parameter that tells the function whether or not to remove NA values from the calculation.
It literally means NA remove. 

## args

args() function in R Language is used to get the required arguments by a function. It takes function name as arguments and returns the arguments that are required by that function.

In [6]:
args(max)

function (..., na.rm = FALSE) 
NULL

In [9]:
args(min)

function (..., na.rm = FALSE) 
NULL

In [2]:
max(10,20,30,NA,4,5) #max func will not work with NA

[1] NA

In [3]:
min(10,20,30,NA,4,5)

[1] NA

Need to remove/exclude Null with function na.rm=TRUE

In [4]:
max(10,20,30,NA,4,5, na.rm=TRUE)

[1] 30

In [13]:
min(10,20,30,NA,4,5, na.rm=TRUE)

[1] 4

## mathematical operation

In [14]:
round(3.147689654678)

[1] 3

In [15]:
args(round)

function (x, digits = 0) 
NULL

In [16]:
round(3.1415, digits=2)

[1] 3.14

In [17]:
factorial(5)

[1] 120

In [18]:
die <-1:6
mean(die)

[1] 3.5

In [19]:
args(mean)

function (x, ...) 
NULL

In [20]:
round(mean(die))

[1] 4

## Working with sample

Sample(input,size,replace=FALSE)

In [21]:
sample(x=1:6,size=1) 

[1] 6

In [22]:
sample(x=1:6,size=3) 

[1] 2 6 1

In [23]:
die <-1:6
sample(die,size=6, replace = TRUE)

[1] 1 3 5 6 5 4

## Writing a function

In [24]:
X <- function(){sum(1:10)}
X()

[1] 55

In [25]:
X <- function(){max(10,2,3,30,45,9,11)}
X()

[1] 45

In [26]:
Y<- function(a,b,c){max(a,b,c)}
Y(2,3,4)

[1] 4

In [27]:
#In R, the c() function returns a vector (a one dimensional array)
X<-(c(41,25,34,19,78,90,29,100))
X

[1]  41  25  34  19  78  90  29 100

In [28]:
avg <- function(y){round(sum(y)/length(y))}
avg(X)

[1] 52

## Mode and which_max

In [29]:
getmode <- function(v){uniqv <- unique(v)
  uniqv[which.max(tabulate(match(v, uniqv)))]}
#which_max Return the Index of the First Maximum Value of a Numeric Vector
#tabulate() function in R Language is used to count the frequency of occurrence of a element in the vector
#match returns a vector of the positions of (first) matches of its first argument in its second.
getmode(X) 

[1] 41

In [30]:
#If we have three variables -we use function(x,y,z){formula}
name_targetvariable <- function(x,y,z){max(x,y,z)}
name_targetvariable(10,20,11)

[1] 20

## Vectors in R

Single element vector

In [31]:
x<-100

Multiple elements vector

In [32]:
y<-c(45,50,31,12,18,10,25,41,40,32,20,19)

creating Multiple vectors by using 3 ways 1) operator, 2)seq()function and 3) c()function

Way to list 123-134

In [33]:
c(123,124,125,126,127,128,129,130,131,132,133,134)   #c function

[1] 123 124 125 126 127 128 129 130 131 132 133 134

In [34]:
123:134                           #operator
c(123:134)                            

[1] 123 124 125 126 127 128 129 130 131 132 133 134

[1] 123 124 125 126 127 128 129 130 131 132 133 134

In [35]:
seq(from=123, to=134,by=1)  # seq() function

[1] 123 124 125 126 127 128 129 130 131 132 133 134

## Type of Vectors

In [36]:
a <- 100                         #double  
typeof(a)

[1] "double"

In [37]:
b <-"Sathish"                     #character
typeof(b)

[1] "character"

In [38]:
c <- TRUE                        #Logical
typeof(c)

[1] "logical"

In [39]:
d<- 1L                          #Integer
typeof(d)

[1] "integer"

In [40]:
e <- 2+3i                       #complex
typeof(e)

[1] "complex"

## Arithmetic operations on Vectors

In [41]:
a<-10:15
b<-20:25
a+b
b-a
a*b
b/a
round(b/a)

[1] 30 32 34 36 38 40

[1] 10 10 10 10 10 10

[1] 200 231 264 299 336 375

[1] 2.000000 1.909091 1.833333 1.769231 1.714286 1.666667

[1] 2 2 2 2 2 2

## Matrices

matrix_name <-matrix(data,nrow,ncol,byrow,dimnames)

In [42]:
x<- matrix(c(10:18),nrow=3,byrow=TRUE)
x

[,1] [,2] [,3]
[1,] 10   11   12  
[2,] 13   14   15  
[3,] 16   17   18

In [43]:
y<- matrix(c(100:115),nrow=4,byrow = TRUE)
y

[,1] [,2] [,3] [,4]
[1,] 100  101  102  103 
[2,] 104  105  106  107 
[3,] 108  109  110  111 
[4,] 112  113  114  115

In [44]:
z<- matrix(c(10:21),nrow=4,byrow = FALSE)
z

[,1] [,2] [,3]
[1,] 10   14   18  
[2,] 11   15   19  
[3,] 12   16   20  
[4,] 13   17   21

## Names row and columns 

In [45]:
z<-matrix(c(10:21),nrow=4,byrow=FALSE, dimnames =list(rownames<-c("row1","row2","row3", "row4"),
                                                      colnames<-c("col1","col2","col3")))
z

col1 col2 col3
row1 10   14   18  
row2 11   15   19  
row3 12   16   20  
row4 13   17   21

In [46]:
y
y[2,3]
y[3,] #entire third row
y[,2] #entire second column

[,1] [,2] [,3] [,4]
[1,] 100  101  102  103 
[2,] 104  105  106  107 
[3,] 108  109  110  111 
[4,] 112  113  114  115

[1] 106

[1] 108 109 110 111

[1] 101 105 109 113

In [47]:
x<- matrix(c(10:18),nrow=3,byrow=TRUE)
x

y<- matrix(c(100:108),nrow=3,byrow = TRUE)
y

x+y
y-x
x*y
y/x
round(y/x)

[,1] [,2] [,3]
[1,] 10   11   12  
[2,] 13   14   15  
[3,] 16   17   18

[,1] [,2] [,3]
[1,] 100  101  102 
[2,] 103  104  105 
[3,] 106  107  108

[,1] [,2] [,3]
[1,] 110  112  114 
[2,] 116  118  120 
[3,] 122  124  126

[,1] [,2] [,3]
[1,] 90   90   90  
[2,] 90   90   90  
[3,] 90   90   90

[,1] [,2] [,3]
[1,] 1000 1111 1224
[2,] 1339 1456 1575
[3,] 1696 1819 1944

[,1]      [,2]     [,3]
[1,] 10.000000 9.181818 8.5 
[2,]  7.923077 7.428571 7.0 
[3,]  6.625000 6.294118 6.0

[,1] [,2] [,3]
[1,] 10   9    8   
[2,]  8   7    7   
[3,]  7   6    6

## Arrays in R

syntax -> Var_names<-array(data, dim=c(row,cols,matrices),dimnames)

In [48]:
A <- array(c(1:9),dim=c(3,3,2))
A
dim(A)

, , 1

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

, , 2

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

[1] 3 3 2

In [49]:
B <- array(c(11:20),dim=c(3,3,2))
B
dim(B)

, , 1

     [,1] [,2] [,3]
[1,]   11   14   17
[2,]   12   15   18
[3,]   13   16   19

, , 2

     [,1] [,2] [,3]
[1,]   20   13   16
[2,]   11   14   17
[3,]   12   15   18

[1] 3 3 2

In [50]:
C <- array(c(11:14,21:24,31:34),dim=c(2,2,3))
C
dim(C)

, , 1

     [,1] [,2]
[1,]   11   13
[2,]   12   14

, , 2

     [,1] [,2]
[1,]   21   23
[2,]   22   24

, , 3

     [,1] [,2]
[1,]   31   33
[2,]   32   34

[1] 2 2 3

In [51]:
C[2,2,3]   #to access 2nd row of matrices
C[2,,]     #to access 1st column of matrices
C[,1,]    

[1] 34

[,1] [,2] [,3]
[1,] 12   22   32  
[2,] 14   24   34

[,1] [,2] [,3]
[1,] 11   21   31  
[2,] 12   22   32

## Operations on Arrays

Syntax -> Var_names=apply(array_name,c(1 or 2), function)

In [52]:
r=apply(C,c(1),max)
r
C

[1] 33 34

, , 1

     [,1] [,2]
[1,]   11   13
[2,]   12   14

, , 2

     [,1] [,2]
[1,]   21   23
[2,]   22   24

, , 3

     [,1] [,2]
[1,]   31   33
[2,]   32   34

In [53]:
t=apply(C,c(1),min)
t

[1] 11 12

In [54]:
u=apply(C,c(2),min)
u

[1] 11 13

## getwd and setwd function

In [55]:
getwd() # returns an absolute filepath representing the current working directory of the R process
#setwd("C:/Users/Acer/Desktop")


[1] "C:/Users/sathi/Videos"

## Creating a Data Frame

In [56]:
Roll_no <- seq(from=121,to=130,by=1) 
#seq generate regular sequences
names <- c("A","B","C","D","E","F","G","I","J", "H")
date <- c("15/12/1990","01/12/1990","31/12/1990","10/01/1991","01/01/1991","10/01/1991","01/12/1990","12/01/1991",
          "01/01/1991","10/01/1991")
class(date) # gives the class of the list

[1] "character"

In [57]:
dob <- as.Date(date,"%d/%m/%Y")
#as.Date functions to convert between character representations and objects of class "Date" representing calendar dates.
class(dob)

[1] "Date"

In [58]:
bstat <-c(28,20,21,6,20,15,4,18,9,12)
btrics <- c(25,21,16,9,16,20,6,22,12,10)
micro <- c(20,25,14,14,11,12,10,16,9,11)
maths <- c(18,25,22,4,15,18,2,20,8,NaN)

MA_First <- data.frame(Roll_no,names,dob,bstat,btrics,micro,maths)
MA_First

Roll_no names dob        bstat btrics micro maths
1  121     A     1990-12-15 28    25     20     18  
2  122     B     1990-12-01 20    21     25     25  
3  123     C     1990-12-31 21    16     14     22  
4  124     D     1991-01-10  6     9     14      4  
5  125     E     1991-01-01 20    16     11     15  
6  126     F     1991-01-10 15    20     12     18  
7  127     G     1990-12-01  4     6     10      2  
8  128     I     1991-01-12 18    22     16     20  
9  129     J     1991-01-01  9    12      9      8  
10 130     H     1991-01-10 12    10     11    NaN

## Add new variable/Object in existing data frame

In [59]:
macro <- c(18,25,22,4,15,18,2,20,8,12)

MA_First1 <-data.frame(MA_First, macro)
MA_First1

Roll_no names dob        bstat btrics micro maths macro
1  121     A     1990-12-15 28    25     20     18   18   
2  122     B     1990-12-01 20    21     25     25   25   
3  123     C     1990-12-31 21    16     14     22   22   
4  124     D     1991-01-10  6     9     14      4    4   
5  125     E     1991-01-01 20    16     11     15   15   
6  126     F     1991-01-10 15    20     12     18   18   
7  127     G     1990-12-01  4     6     10      2    2   
8  128     I     1991-01-12 18    22     16     20   20   
9  129     J     1991-01-01  9    12      9      8    8   
10 130     H     1991-01-10 12    10     11    NaN   12

## Alternative way to create Data frame

In [60]:
date <- c("15/12/1990","01/12/1990","31/12/1990","10/01/1991",
          "01/01/1991","10/01/1991","01/12/1990","12/01/1991",
          "01/01/1991","10/01/1991")

MA_First <- data.frame(
  Roll_no = seq(from=121,to=130,by=1),
  names = c("A","B","C","D","E","F","G","I","J", "H"),
  dob =as.Date(date,"%d/%m/%Y"),
  bstat =c(28,20,21,6,20,15,4,18,9,12),
  btrics = c(25,21,16,9,16,20,6,22,12,10),
  micro = c(20,25,14,14,11,12,10,16,9,11),
  maths = c(18,25,22,4,15,18,2,20,8,12),
  macro = c(18,25,22,4,15,18,2,20,8,12)
  )
MA_First

Roll_no names dob        bstat btrics micro maths macro
1  121     A     1990-12-15 28    25     20    18    18   
2  122     B     1990-12-01 20    21     25    25    25   
3  123     C     1990-12-31 21    16     14    22    22   
4  124     D     1991-01-10  6     9     14     4     4   
5  125     E     1991-01-01 20    16     11    15    15   
6  126     F     1991-01-10 15    20     12    18    18   
7  127     G     1990-12-01  4     6     10     2     2   
8  128     I     1991-01-12 18    22     16    20    20   
9  129     J     1991-01-01  9    12      9     8     8   
10 130     H     1991-01-10 12    10     11    12    12

Extracting individual rows/ columns from data frame

In [61]:
#Row
MA_First[10,]
MA_First[3,]

Roll_no names dob        bstat btrics micro maths macro
10 130     H     1991-01-10 12    10     11    12    12

Roll_no names dob        bstat btrics micro maths macro
3 123     C     1990-12-31 21    16     14    22    22

In [62]:
#Column
MA_First[,5]
MA_First[,2]

[1] 25 21 16  9 16 20  6 22 12 10

[1] A B C D E F G I J H
Levels: A B C D E F G H I J

In [63]:
#If we dont use comma before/after will work as extracting column works 
MA_First[5]

btrics
1  25    
2  21    
3  16    
4   9    
5  16    
6  20    
7   6    
8  22    
9  12    
10 10

In [64]:
#Extracting consecutive rows/columns
MA_First[7:10,]

Roll_no names dob        bstat btrics micro maths macro
7  127     G     1990-12-01  4     6     10     2     2   
8  128     I     1991-01-12 18    22     16    20    20   
9  129     J     1991-01-01  9    12      9     8     8   
10 130     H     1991-01-10 12    10     11    12    12

In [65]:
MA_First[1:5]

Roll_no names dob        bstat btrics
1  121     A     1990-12-15 28    25    
2  122     B     1990-12-01 20    21    
3  123     C     1990-12-31 21    16    
4  124     D     1991-01-10  6     9    
5  125     E     1991-01-01 20    16    
6  126     F     1991-01-10 15    20    
7  127     G     1990-12-01  4     6    
8  128     I     1991-01-12 18    22    
9  129     J     1991-01-01  9    12    
10 130     H     1991-01-10 12    10

Alternative way to extract column/object by names

In [66]:
MA_First$bstat

[1] 28 20 21  6 20 15  4 18  9 12

In [67]:
MA_First$macro

[1] 18 25 22  4 15 18  2 20  8 12

## Descriptive Statistics

In [68]:
#Average/ Mean
mean(MA_First[,7])

[1] 14.4

In [69]:
mean(bstat)
mean(btrics)
mean(micro)
mean(maths)

[1] 15.3

[1] 15.7

[1] 14.2

[1] NaN

In [70]:
#Median 
median(bstat)
median(btrics)
median(micro)
median(maths)

[1] 16.5

[1] 16

[1] 13

[1] NA

In [71]:
##mode
getmode <- function(v) {uniqv <- unique(v)
  uniqv[which.max(tabulate(match(v, uniqv)))]}
getmode(bstat)
getmode(btrics)
getmode(micro)
getmode(maths)

[1] 20

[1] 16

[1] 14

[1] 18

In [72]:
#Standard Deviation
sd(MA_First$bstat)
sd(btrics)
sd(micro)
sd(maths)

[1] 7.528465

[1] 6.307843

[1] 4.98442

[1] NA

In [73]:
#Variance
(sd(bstat))^2
var(bstat)
var(btrics)
var(micro)
var(maths)

[1] 56.67778

[1] 56.67778

[1] 39.78889

[1] 24.84444

[1] NA

In [74]:
#Covariance, Correlation
cov(MA_First$bstat,MA_First$btrics)
cor(MA_First$bstat,MA_First$btrics)

[1] 41.76667

[1] 0.8795135

In [75]:
MA_First

Roll_no names dob        bstat btrics micro maths macro
1  121     A     1990-12-15 28    25     20    18    18   
2  122     B     1990-12-01 20    21     25    25    25   
3  123     C     1990-12-31 21    16     14    22    22   
4  124     D     1991-01-10  6     9     14     4     4   
5  125     E     1991-01-01 20    16     11    15    15   
6  126     F     1991-01-10 15    20     12    18    18   
7  127     G     1990-12-01  4     6     10     2     2   
8  128     I     1991-01-12 18    22     16    20    20   
9  129     J     1991-01-01  9    12      9     8     8   
10 130     H     1991-01-10 12    10     11    12    12

## Conditional statements

== equal, >= greater than equal, <= less than equal, > greater than only and < less than only

Creating Object/Variable with conditional statement

In [76]:
Result_S <- ifelse(bstat>=12, "its_true","its_false")
Result_S

[1] "its_true"  "its_true"  "its_true"  "its_false" "its_true"  "its_true" 
 [7] "its_false" "its_true"  "its_false" "its_true"

ifelse returns a value with the same shape as test which is filled with elements selected from either yes or no depending on whether the element of test is TRUE or FALSE

In [77]:
which(bstat<12) #which(): The which function in R returns the position of the values in the logical vector

[1] 4 7 9

In [78]:
Result_E <- ifelse(btrics>=12, "PASS","REPEAT")
Result_E

[1] "PASS"   "PASS"   "PASS"   "REPEAT" "PASS"   "PASS"   "REPEAT" "PASS"  
 [9] "PASS"   "REPEAT"

In [79]:
which(btrics<12)

[1]  4  7 10

In [80]:
MA_First1 <- data.frame(MA_First, Result_S, Result_E)
MA_First1

Roll_no names dob        bstat btrics micro maths macro Result_S  Result_E
1  121     A     1990-12-15 28    25     20    18    18    its_true  PASS    
2  122     B     1990-12-01 20    21     25    25    25    its_true  PASS    
3  123     C     1990-12-31 21    16     14    22    22    its_true  PASS    
4  124     D     1991-01-10  6     9     14     4     4    its_false REPEAT  
5  125     E     1991-01-01 20    16     11    15    15    its_true  PASS    
6  126     F     1991-01-10 15    20     12    18    18    its_true  PASS    
7  127     G     1990-12-01  4     6     10     2     2    its_false REPEAT  
8  128     I     1991-01-12 18    22     16    20    20    its_true  PASS    
9  129     J     1991-01-01  9    12      9     8     8    its_false PASS    
10 130     H     1991-01-10 12    10     11    12    12    its_true  REPEAT

In [81]:
Result_SE <- ifelse(bstat+btrics>=24, "PASS","REPEAT")
which(bstat+btrics<24)

[1]  4  7  9 10

## And condition

In [82]:
Result_SE1 <- ifelse (bstat>=12 & btrics>=12, "PASS","REPEAT")
Result_SE1
which(bstat>=12 & btrics>=12)

[1] "PASS"   "PASS"   "PASS"   "REPEAT" "PASS"   "PASS"   "REPEAT" "PASS"  
 [9] "REPEAT" "REPEAT"

[1] 1 2 3 5 6 8

In [83]:
MA_First2 <-data.frame(MA_First, Result_SE1)
MA_First2

Roll_no names dob        bstat btrics micro maths macro Result_SE1
1  121     A     1990-12-15 28    25     20    18    18    PASS      
2  122     B     1990-12-01 20    21     25    25    25    PASS      
3  123     C     1990-12-31 21    16     14    22    22    PASS      
4  124     D     1991-01-10  6     9     14     4     4    REPEAT    
5  125     E     1991-01-01 20    16     11    15    15    PASS      
6  126     F     1991-01-10 15    20     12    18    18    PASS      
7  127     G     1990-12-01  4     6     10     2     2    REPEAT    
8  128     I     1991-01-12 18    22     16    20    20    PASS      
9  129     J     1991-01-01  9    12      9     8     8    REPEAT    
10 130     H     1991-01-10 12    10     11    12    12    REPEAT

## Or condition

In [84]:
Result_SE2 <- ifelse (bstat>=12 | btrics>=12, "PASS","REPEAT") # bstat or btrics >=12
Result_SE2
which(bstat>=12 | btrics>=12)

[1] "PASS"   "PASS"   "PASS"   "REPEAT" "PASS"   "PASS"   "REPEAT" "PASS"  
 [9] "PASS"   "PASS"

[1]  1  2  3  5  6  8  9 10

## subset

Creating a subset of data frame with conditional statement

In [85]:
MA_First_Repeat <- subset(MA_First2, Result_SE2=="REPEAT")
MA_First_Repeat

Roll_no names dob        bstat btrics micro maths macro Result_SE1
4 124     D     1991-01-10 6     9      14    4     4     REPEAT    
7 127     G     1990-12-01 4     6      10    2     2     REPEAT

create a subset of data where students have failed in either Econometrics or statistics

In [86]:
Remedial1 <-subset(MA_First2,bstat<12 |btrics <12)
Remedial1

Roll_no names dob        bstat btrics micro maths macro Result_SE1
4  124     D     1991-01-10  6     9     14     4     4    REPEAT    
7  127     G     1990-12-01  4     6     10     2     2    REPEAT    
9  129     J     1991-01-01  9    12      9     8     8    REPEAT    
10 130     H     1991-01-10 12    10     11    12    12    REPEAT

Create a subset of data where students have failed in both Econometrics and statistics

In [87]:
Remedial1 <-subset(MA_First2,bstat<12 & btrics <12)
Remedial1

Roll_no names dob        bstat btrics micro maths macro Result_SE1
4 124     D     1991-01-10 6     9      14    4     4     REPEAT    
7 127     G     1990-12-01 4     6      10    2     2     REPEAT

## wrtie.table and wrie.csv

Most flexible command for exporting data from R is write.table

In [88]:
#Save the file in current working directory, save it as a .CSV file format
 # write.table(MA_First,file = "MA_First.csv",sep=",")

In [89]:
#export without row names by setting the row.names=FALSE
# write.table(MA_First,file = "MA_First.csv", row.names= FALSE,sep=",",)

In [90]:
#How to export a file from R into a different working directory
# write.table(MA_First,file = "C:/Users/Acer/Desktop/", row.names= FALSE,sep=",")

In [91]:
#To Export data from R into a comma separated value file (.CSV) use
write.csv(MA_First,file = "MA_First.csv", row.names= FALSE)

In [92]:
#To Export data in Excel need to install package xlsx
# install.packages("xlsx")
# library(xlsx)
# write.xlsx(MA_First, file="MA_Firsts.xlsx", row.names= FALSE)

## Working with csv

In [93]:
coviddata<- read.csv("F:\\python\\coviddata.csv")
dim(coviddata)
nrow(coviddata)
ncol(coviddata)
summary(coviddata)
head(coviddata,10)
tail(coviddata)
tail(coviddata,10)

[1] 500   3

[1] 500

[1] 3

      City           Cases         Vaccinated   
 Min.   :  1.0   Min.   :   11   Min.   :  316  
 1st Qu.:125.8   1st Qu.: 6095   1st Qu.:12372  
 Median :250.5   Median :12572   Median :25774  
 Mean   :250.5   Mean   :12558   Mean   :25022  
 3rd Qu.:375.2   3rd Qu.:19271   3rd Qu.:37805  
 Max.   :500.0   Max.   :24976   Max.   :49667  

City Cases Vaccinated
1   1   20258 47774     
2   2   16449 26085     
3   3    6666 28382     
4   4   19939 12349     
5   5   21648  1725     
6   6   14702 41653     
7   7    1534 37952     
8   8   24098  5703     
9   9    4001 23527     
10 10   11690 11442

City Cases Vaccinated
495 495  17635 30360     
496 496  12449 38358     
497 497   6030 19177     
498 498   7899   382     
499 499  16347 32509     
500 500   7871 39519

City Cases Vaccinated
491 491  18826 49428     
492 492  10385 44836     
493 493   2331  9361     
494 494    997 22391     
495 495  17635 30360     
496 496  12449 38358     
497 497   6030 19177     
498 498   7899   382     
499 499  16347 32509     
500 500   7871 39519

Assigning/renaming column names to the data if does not have

In [94]:
colnames(coviddata)

[1] "City"       "Cases"      "Vaccinated"

In [95]:
colnames(coviddata) <-c("State", "Covid case", "dose")
colnames(coviddata)

[1] "State"      "Covid case" "dose"